# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 06:23
from __future__ import unicode_literals

import dashboard.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_document_emailid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(upload_to='documents/clientCertificates/%Y/%m/%d', validators=[dashboard.validators.validate_file_extension]),
        ),
    ]
