# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 11:22
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20170222_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='domain_name',
            field=models.TextField(default='null', validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AddField(
            model_name='document',
            name='uplaod_timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
