# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 06:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_document_hostname'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsrRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(default='null', max_length=100)),
                ('organization', models.CharField(default='null', max_length=60)),
                ('department', models.CharField(default='null', max_length=60)),
                ('city', models.CharField(default='null', max_length=100)),
                ('state', models.CharField(default='null', max_length=100)),
                ('country', models.CharField(default='null', max_length=60)),
                ('keysize', models.CharField(default='null', max_length=60)),
                ('admin_emailid', models.CharField(default='null', max_length=200)),
                ('requester_emailid', models.CharField(default='null', max_length=200)),
                ('csr_file_name', models.CharField(default='null', max_length=200)),
                ('key_file_name', models.CharField(default='null', max_length=200)),
                ('timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
