# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 16:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_csrrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='hostname',
            new_name='tldr_name',
        ),
    ]
